<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>

        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.8.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
        <PackageReference Include="NUnit" Version="3.13.2" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
        <PackageReference Include="coverlet.collector" Version="3.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\src.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day1-test.txt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day1.txt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day2-test.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day2.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day3.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day3-test.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day4-test.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day4.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day4-bonus.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day5-test.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day5.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day6-test.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day6.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day7-test.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day7.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day9-test.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="gianlucadurelli\adventofcode\year2025\resources\day9.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
